@Tags(['launcher-icons'])
library;

import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter_test/flutter_test.dart';

import 'launcher_icon_spec.dart';
import 'rgb_png.dart';

/// Regenerates every Android and iOS launcher icon from the user's logo,
/// [LauncherIconSpec.sourcePath]. Skipped in normal runs (`dart_test.yaml`).
/// Run it after the logo changes:
///
///     flutter test --tags launcher-icons --run-skipped test/brand/generate_launcher_icons_test.dart
///
/// The logo is a rounded-square tile with transparent corners. Each
/// platform gets it in the form it expects:
///
/// - Android 8+ (adaptive icon): the tile on a foreground layer, sized so the
///   artwork fits the 66 dp safe zone; the background layer is the tile's own
///   edge colour, so any launcher mask shape shows only the tile's colours.
/// - Android 7 (legacy icon): the tile itself, on a transparent square.
/// - Android 12+ splash screen: the tile, with its own rounded corners, in
///   the middle of the splash icon canvas.
/// - iOS: the tile filling an opaque square (iOS rounds the corners itself,
///   and the App Store refuses an icon with an alpha channel).
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('writes the Android and iOS launcher icons', () async {
    final source = await _decode(File(LauncherIconSpec.sourcePath));
    final pixels = await _straightRgba(source);
    final tile = _opaqueBounds(source, pixels);
    final edge = _edgeColour(source, pixels, tile);
    final artworkRadius = _artworkRadius(source, pixels, tile);

    // The adaptive foreground: the tile scaled so a circle around all of the
    // artwork is LauncherIconSpec.safeZoneDp wide.
    final adaptiveTileDp =
        LauncherIconSpec.safeZoneDp / 2 * tile.width / artworkRadius;

    for (final MapEntry(key: folder, value: scale)
        in LauncherIconSpec.androidDensities.entries) {
      final res = '${LauncherIconSpec.androidRes}/$folder';

      final legacySize = (LauncherIconSpec.legacyDp * scale).round();
      final legacyTile = LauncherIconSpec.legacyTileDp * scale;
      await _writeRgbaPng(
        '$res/${LauncherIconSpec.legacyFile}',
        await _render(legacySize, (canvas) {
          _drawTile(canvas, source, tile, _centred(legacySize, legacyTile));
        }),
      );

      final splashSize = (LauncherIconSpec.splashCanvasDp * scale).round();
      final splashTile = LauncherIconSpec.splashTileDp * scale;
      final drawables =
          '${LauncherIconSpec.androidRes}/'
          '${LauncherIconSpec.drawableFolder(folder)}';
      Directory(drawables).createSync();
      await _writeRgbaPng(
        '$drawables/${LauncherIconSpec.splashFile}',
        await _render(splashSize, (canvas) {
          _drawTile(canvas, source, tile, _centred(splashSize, splashTile));
        }),
      );

      final foregroundSize = (LauncherIconSpec.adaptiveDp * scale).round();
      final foregroundTile = adaptiveTileDp * scale;
      await _writeRgbaPng(
        '$res/${LauncherIconSpec.foregroundFile}',
        await _render(foregroundSize, (canvas) {
          _drawTile(
            canvas,
            source,
            tile,
            _centred(foregroundSize, foregroundTile),
          );
        }),
      );
    }

    File(LauncherIconSpec.backgroundColourPath).writeAsStringSync(
      '<?xml version="1.0" encoding="utf-8"?>\n'
      '<!-- Generated by test/brand/generate_launcher_icons_test.dart from\n'
      '     the logo\'s edge colour. Do not edit by hand. -->\n'
      '<resources>\n'
      '    <color name="ic_launcher_background">'
      '${_hex(edge)}</color>\n'
      '</resources>\n',
    );

    for (final image in iosAppIcons()) {
      final size = image.pixels;
      final icon = await _render(size, (canvas) {
        final square = Rect.fromLTWH(0, 0, size.toDouble(), size.toDouble());
        canvas.drawRect(square, Paint()..color = edge);
        _drawTile(canvas, source, tile, square);
      });
      final rgba = await _straightRgba(icon);
      File('${LauncherIconSpec.iosIconSet}/${image.filename}')
          .writeAsBytesSync(encodeRgbPng(size, size, rgba));
      icon.dispose();
    }

    // Recorded so a reviewer can see what the generator measured.
    // ignore: avoid_print
    print(
      'launcher icons: tile ${tile.width.round()}x${tile.height.round()} px, '
      'artwork radius ${artworkRadius.round()} px, adaptive tile '
      '${adaptiveTileDp.toStringAsFixed(1)} dp, background ${_hex(edge)}',
    );
  });
}

Future<Image> _decode(File file) async {
  final codec = await instantiateImageCodec(file.readAsBytesSync());
  return (await codec.getNextFrame()).image;
}

Future<Uint8List> _straightRgba(Image image) async =>
    (await image.toByteData(format: ImageByteFormat.rawStraightRgba))!.buffer
        .asUint8List();

int _alpha(Image image, Uint8List pixels, int x, int y) =>
    pixels[(y * image.width + x) * 4 + 3];

double _luminance(Image image, Uint8List pixels, int x, int y) {
  final i = (y * image.width + x) * 4;
  return 0.2126 * pixels[i] + 0.7152 * pixels[i + 1] + 0.0722 * pixels[i + 2];
}

/// The bounds of the logo's tile: every pixel that is at least half opaque.
Rect _opaqueBounds(Image image, Uint8List pixels) {
  var left = image.width, top = image.height, right = -1, bottom = -1;
  for (var y = 0; y < image.height; y++) {
    for (var x = 0; x < image.width; x++) {
      if (_alpha(image, pixels, x, y) >= 128) {
        left = math.min(left, x);
        right = math.max(right, x);
        top = math.min(top, y);
        bottom = math.max(bottom, y);
      }
    }
  }
  return Rect.fromLTRB(
    left.toDouble(),
    top.toDouble(),
    right + 1.0,
    bottom + 1.0,
  );
}

/// The average colour of a band just inside the tile's four straight edges.
Color _edgeColour(Image image, Uint8List pixels, Rect tile) {
  final from = (tile.width * 0.25).round(), to = (tile.width * 0.75).round();
  var r = 0, g = 0, b = 0, n = 0;
  void add(int x, int y) {
    final i = (y * image.width + x) * 4;
    r += pixels[i];
    g += pixels[i + 1];
    b += pixels[i + 2];
    n++;
  }

  final left = tile.left.round(), top = tile.top.round();
  final right = tile.right.round() - 1, bottom = tile.bottom.round() - 1;
  for (
    var inset = LauncherIconSpec.edgeBandStart;
    inset < LauncherIconSpec.edgeBandEnd;
    inset++
  ) {
    for (var t = from; t < to; t++) {
      add(left + t, top + inset);
      add(left + t, bottom - inset);
      add(left + inset, top + t);
      add(right - inset, top + t);
    }
  }
  return Color.fromARGB(255, r ~/ n, g ~/ n, b ~/ n);
}

/// How far the artwork (anything clearly lighter than the tile) reaches from
/// the tile's centre.
double _artworkRadius(Image image, Uint8List pixels, Rect tile) {
  const inset = LauncherIconSpec.edgeBandEnd;
  final centre = tile.center;
  var radius = 0.0;
  for (var y = tile.top.round() + inset; y < tile.bottom - inset; y++) {
    for (var x = tile.left.round() + inset; x < tile.right - inset; x++) {
      if (_luminance(image, pixels, x, y) > LauncherIconSpec.artworkLuminance) {
        radius = math.max(radius, (Offset(x + 0.5, y + 0.5) - centre).distance);
      }
    }
  }
  return radius;
}

Rect _centred(int canvas, double side) => Rect.fromCenter(
  center: Offset(canvas / 2, canvas / 2),
  width: side,
  height: side,
);

void _drawTile(Canvas canvas, Image source, Rect tile, Rect target) {
  canvas.drawImageRect(
    source,
    tile,
    target,
    Paint()
      ..filterQuality = FilterQuality.high
      ..isAntiAlias = true,
  );
}

Future<Image> _render(int size, void Function(Canvas canvas) paint) {
  final recorder = PictureRecorder();
  paint(
    Canvas(recorder, Rect.fromLTWH(0, 0, size.toDouble(), size.toDouble())),
  );
  final picture = recorder.endRecording();
  return picture.toImage(size, size).whenComplete(picture.dispose);
}

Future<void> _writeRgbaPng(String path, Image image) async {
  final png = await image.toByteData(format: ImageByteFormat.png);
  File(path).writeAsBytesSync(png!.buffer.asUint8List());
  image.dispose();
}

String _hex(Color colour) {
  String channel(double v) =>
      (v * 255).round().toRadixString(16).padLeft(2, '0').toUpperCase();
  return '#${channel(colour.r)}${channel(colour.g)}${channel(colour.b)}';
}
